### ISSUE TITLE
Do we use XMLs in USPTO_CPC?

### ISSUE THREAD

**Issue by mayalroy** [gmoore016/USPTO_Data_Guide#1]
Hi @heidiliewilliams!

I'm working on the wiki page for /raw/USPTO_CPC/, and I was wondering whether we currently use the XML files in this directory for any build files? I don't see any files that currently parse this data, but I thought I'd check in with you to make sure.

**Comment by heidiliewilliams** [comment]
good question @mayalroy -- I am not sure.  I think there might be a way to "search" our directories for that extension to check?

**Comment by gmoore016** [comment]
Ah, I was just going through my GitHub notifications and saw this by coincidence! Sorry for coming in two months late. Can confirm that as far as I know we don't use the CPC data--it was part of the USPTO bulk data repository, meaning it was easy to scrape, so we decided to download it just so we knew we had it. I'm relatively confident it was never used though!
