### ISSUE TITLE
Data sources changed/not public

### ISSUE THREAD

**Issue by mayalroy** [gmoore016/USPTO_Data_Guide#4]
@heidiliewilliams -- There are two more data sets listed on the main page of this GitHub project that I have yet to document: IMS_drug_patents and PatentLens. For both of these, I am not quite sure how to proceed with documenting them in a way that is useful for a public data guide and would appreciate any of your thoughts!

The IMS_drug_patents directory on Sherlock looks like it was shared specifically with you by Margaret Kyle. It was built from data published by IMS in the LifeCycle database, but I actually can't find a publicly accessible version of that database's documentation. The data set on Sherlock is actually a combination of several data sets published by IMS but I don't think we have the code or the list of steps taken to turn those data sets into the one we have saved. Did you have something in mind for how to include this in the data guide?

For the PatentLens data, it looks like Patent Lens is now Lens, and none of the links in the documentation of the data on Sherlock work any more. I tried looking around the Lens website, but I can't seem to find where these data sets would be downloaded from now. Do you have any suggestions for where I might look for this data? And if we learn that it is no longer available to new users in the same form as the data currently on Sherlock, is it still worthwhile to document this data set in the public data guide?

**Comment by heidiliewilliams** [comment]
Thanks!  we should skip both of these!

**Comment by mayalroy** [comment]
Sounds good!
