### ISSUE TITLE
Adding patent data idiosyncrasies page

### ISSUE THREAD

**Issue by mayalroy** [gmoore016/USPTO_Data_Guide#5]
@heidiliewilliams -- In addition to the data set-specific pages that I've set up, I think it might be helpful to include a page on the various idiosyncrasies in the USPTO data that a new user might take a long time to find on their own. Here are a few examples that come to mind:

- check digits -- Explaining what they are, which years they were used, and some recommendations for handling them in the data
- switches between patent classification systems -- The USPTO has switched its preferred patent classification system several times, so adding some brief notes on the various systems and when they are used might be helpful.
- withdrawn patents -- Notes on how withdrawn patents show up in various data sets (are they totally removed? just the patent number with no other information? are they left intact?) and how to use the USPTO list of withdrawn patents to find/drop them

Do you think a page like this would be helpful and a good addition to the wiki? @gmoore016, if you have any thoughts on USPTO data quirks that would fit a page like this, feel free to chime in!

**Comment by heidiliewilliams** [comment]
yes, I agree!!  These are I think currently in some other GitHub page of ours @mayalroy -- is that right?
