### ISSUE TITLE
Publicly available GS Patent Examiner data

### ISSUE THREAD

**Issue by mayalroy** [gmoore016/USPTO_Data_Guide#6]
@heidiliewilliams -- I'm reviewing the wiki page for the [GS_patent](https://github.com/liegroup-stanford/GS_patent) data on USPTO patent examiners. I realized that it seems like our version of the data was directly shared with you by Michael Frakes, so our documentation on Sherlock is for that specific version of the data and includes some pre-processed files that a new user may not have. How should the Data Guide address this? Is there a publicly accessible version of the data that I should point to on the wiki?

From my read of the [data appendix](https://data.nber.org/data-appendix/w20337/frakes_wasserman_restat_APPENDIX.pdf) of [Frakes and Wasserman (2017)](https://www.mitpressjournals.org/doi/abs/10.1162/REST_a_00605?af=R&mobileUi=0), it seems like they start from the PAIR database but I can't tell exactly how one would construct the data that we have on Sherlock.

**Comment by heidiliewilliams** [comment]
good question -- I would skip putting this on the data guide.  Thanks!
